---
title: "Bootstrapping"
output: github_document
date: 11/23/2020
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Simulate data

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = 
  sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

Plot the datasets

```{r}
sim_df_const %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() + 
  geom_smooth(method = "lm")

sim_df_nonconst %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
lm(y ~ x, data = sim_df_const) %>% broom::tidy()
lm(y ~ x, data = sim_df_nonconst) %>% broom::tidy()
```

## Draw one bottstrap sample

```{r}
boot_sample = function(df) {
  
  sample_frac(df, size = 1, replace = TRUE) %>%  # You want the size of the sample to be the same
      arrange(x)                                 # REPLACE makes the sample not be always the same
}
```

Check if this works

```{r}
boot_sample(sim_df_nonconst) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point(alpha = .3) + 
  geom_smooth(method = "lm") +
  ylim(-5, 16)
```

```{r}
boot_sample(sim_df_nonconst) %>% 
  lm(y ~ x, data = .) %>% 
  broom::tidy()
```
